"""Command-line interface.

Every interface (CLI, chat, cron, MCP server) calls the same engine, so there
is one implementation of the analysis and several ways to reach it — all of
them plain terminal I/O or structured data, no GUI.
"""

from __future__ import annotations

import argparse
import sys
from datetime import date

import anyio
from rich.console import Console
from rich.table import Table

from mybroker.config import REPORTS_DIR, ensure_dirs
from mybroker.portfolio.loader import load_portfolio
from mybroker.portfolio.metrics import snapshot
from mybroker.portfolio.policy import Policy

# stdout: the actual thing someone ran a command to see (tables, reports).
# stderr: chrome around that -- auth status, progress, "next steps" menus.
# Piping `factfolio status > snapshot.txt` should capture the snapshot, not
# also the "Running review..." line -- same split the old print(..., file=
# sys.stderr) calls already made, just through Rich now for the parts that
# render as tables or need a live-updating status line.
console = Console()
err_console = Console(stderr=True)

_ACTION_STYLE = {"BUY": "green", "SELL": "red", "TRIM": "yellow", "HOLD": "cyan", "WATCH": "dim"}

_POLICY_TEMPLATE = """\
# Investment Policy

**Status:** DRAFT — edit every number below before relying on this.

This is the standard every recommendation is measured against. The agent
does not decide whether a position is too large; this file decides, and
the agent reasons about what to do next. Change the numbers here and the
agent's behaviour changes with them.

The fenced `yaml` block is parsed by the code. The prose around it should
explain *why* each number is what it is, so the two never drift apart —
edit both together.

## Objective

State your target CAGR and horizon here, and why: e.g. "13% CAGR over 10
years — roughly the Nifty's long-run average, prioritising low drawdown
over outperformance."

## Structure: core–satellite

Describe what belongs in each bucket for you (index funds/large-caps vs.
midcap/smallcap/thematic bets), and your current split.

## Position limits

Describe your position/sector/speculative caps and why — the numbers below
are generic starting points, not a recommendation.

## Rebalancing approach

New capital first, or trim-to-cap, or something else — and your rule for
when a sale is actually justified given its tax cost.

---

```yaml
# ── Machine-enforceable limits. Parsed by portfolio/policy.py ──
# Generic starting values — replace every one of these with your own.
target_cagr_pct: 12.0

core_min_pct: 60.0
core_max_pct: 70.0

# Optional dated glidepath — delete this block entirely to use core_min_pct
# as a flat target from day one instead of a phased-in one.
# glidepath_start: YYYY-MM-DD
# glidepath:
#   - {months: 6,  core_pct: 30.0}
#   - {months: 12, core_pct: 45.0}

max_position_pct: 8.0                 # any single core holding
max_satellite_position_pct: 5.0       # any single satellite holding
max_sector_pct: 25.0                  # any one sector

speculative_cap_pct: 10.0
speculative_symbols: []               # e.g. [IDEA, YESBANK] — binary-outcome names

min_positions: 8
max_positions: 25

monthly_capital: 0                    # new capital available per month, in ₹
max_annual_turnover_pct: 25.0
```

---

## Change log

| Date | Change |
|---|---|
| __TODAY__ | Generated by `factfolio init`. Not yet customised or approved. |
"""

DIM, BOLD, RESET = "\033[2m", "\033[1m", "\033[0m"
RED, YELLOW, GREEN = "\033[31m", "\033[33m", "\033[32m"

SEVERITY_STYLE = {"critical": "red", "high": "red", "medium": "yellow", "low": "dim"}


def _auth_status_line() -> str:
    """Which credential the Claude Agent SDK will actually use.

    Neither `agents/orchestrator.py` nor `agents/chat.py` sets an API key —
    the subprocess just inherits this process's environment, so the
    resolution is entirely the `claude` CLI's own: ANTHROPIC_API_KEY, if
    set, wins; otherwise it falls back to a local `claude login` session.
    Local login is therefore the default with zero configuration, and
    exporting the env var is the override — never the other way around.
    """
    import os

    if os.environ.get("ANTHROPIC_API_KEY"):
        return f"{DIM}auth: ANTHROPIC_API_KEY (env var override){RESET}"
    return f"{DIM}auth: local `claude login` session (no ANTHROPIC_API_KEY set){RESET}"


def cmd_status(_args) -> int:
    """Deterministic portfolio status. No LLM, no network, instant."""
    snap = snapshot(load_portfolio())
    pol = Policy.load()
    target, step = pol.current_core_target()

    pnl_style = "green" if snap.total_pnl >= 0 else "red"
    console.print()
    console.print("[bold]Portfolio[/bold] [dim](from holdings.csv)[/dim]")
    console.print(f"  Invested       ₹{snap.total_invested:>14,.2f}")
    console.print(f"  Current        ₹{snap.total_value:>14,.2f}")
    console.print(
        f"  P&L            [{pnl_style}]₹{snap.total_pnl:>14,.2f}  "
        f"({snap.total_pnl_pct:+.2f}%)[/{pnl_style}]"
    )

    console.print()
    console.print("[bold]Allocation[/bold]")
    console.print(
        f"  Core           {snap.core_pct:>6.1f}%   "
        f"[dim]target now {target:.0f}% ({step}); final {pol.core_min_pct:.0f}%[/dim]"
    )
    console.print(f"  Satellite      {snap.satellite_pct:>6.1f}%")

    console.print()
    positions = Table(title="Top positions", header_style="bold", show_edge=False)
    positions.add_column("Symbol")
    positions.add_column("Weight", justify="right")
    positions.add_column("Value", justify="right")
    positions.add_column("P&L", justify="right")
    positions.add_column("Sector", style="dim")
    for w in snap.positions[:8]:
        style = "green" if w.pnl >= 0 else "red"
        positions.add_row(
            w.key, f"{w.weight_pct:.1f}%", f"₹{w.value:,.0f}",
            f"[{style}]{w.pnl_pct:+.1f}%[/{style}]", w.sector,
        )
    console.print(positions)

    console.print()
    sectors = Table(title="Sectors", header_style="bold", show_edge=False)
    sectors.add_column("Sector")
    sectors.add_column("Weight", justify="right")
    sectors.add_column("")
    for w in snap.sectors[:6]:
        over = w.weight_pct > pol.max_sector_pct
        flag = f"[red]← over {pol.max_sector_pct:.0f}% cap[/red]" if over else ""
        sectors.add_row(w.key, f"{w.weight_pct:.1f}%", flag)
    console.print(sectors)

    breaches = pol.check(snap)
    console.print()
    console.print(f"[bold]Policy[/bold] [dim]({len(breaches)} breaches)[/dim]")
    if breaches:
        policy_table = Table(header_style="bold", show_edge=False)
        policy_table.add_column("Severity")
        policy_table.add_column("Subject")
        policy_table.add_column("Actual", justify="right")
        policy_table.add_column("Limit", justify="right")
        for b in breaches[:10]:
            style = SEVERITY_STYLE.get(b.severity, "")
            policy_table.add_row(
                f"[{style}]{b.severity}[/{style}]" if style else b.severity,
                b.subject, f"{b.actual:.1f}%", f"{b.limit:.0f}%",
            )
        console.print(policy_table)
        if len(breaches) > 10:
            console.print(f"  [dim]… and {len(breaches) - 10} more[/dim]")

    pc, sc = snap.position_concentration, snap.sector_concentration
    console.print()
    console.print("[bold]Concentration[/bold]")
    console.print(f"  Position HHI   {pc.hhi:>6.0f}  ({pc.verdict})")
    console.print(f"  Sector HHI     {sc.hhi:>6.0f}  ({sc.verdict})")
    if sc.hhi > pc.hhi:
        console.print(
            "  [dim]Sector HHI exceeds position HHI — position-level HHI is[/dim]"
        )
        console.print(
            "  [dim]correlation-blind, so the sector reading is the honest one.[/dim]"
        )

    for w in snap.warnings:
        console.print(f"\n  [yellow]![/yellow] {w}")
    console.print()
    return 0


def _render_recommendations(recs: list) -> None:
    """One row per recommendation actually logged this run — the real
    BUY/SELL/HOLD decision and why, not a wall of markdown to scroll
    through to find it. The full report (with everything else the agents
    found) is still written to reports/ either way."""
    if not recs:
        console.print("[dim]No recommendations were logged this run.[/dim]")
        return

    table = Table(title="Recommendations", header_style="bold", show_lines=True)
    table.add_column("Symbol", style="bold", no_wrap=True)
    table.add_column("Action", no_wrap=True)
    table.add_column("Conviction", no_wrap=True)
    table.add_column("Rationale", max_width=56)
    table.add_column("Key evidence", max_width=34, style="dim")

    for r in recs:
        style = _ACTION_STYLE.get(r.action, "")
        action = f"[{style}]{r.action}[/{style}]" if style else r.action
        evidence = "\n".join(
            f"{e.get('tool', '?')}.{e.get('field', '?')}={e.get('value', '?')}"
            for e in (r.evidence or [])[:3]
        )
        table.add_row(r.symbol, action, r.conviction, r.rationale, evidence)

    console.print(table)


def cmd_report(args) -> int:
    """Full agent-generated review, written to reports/YYYY-MM-DD.md."""
    from mybroker.agents.orchestrator import run_review
    from mybroker.ledger import recommendations_for_run

    ensure_dirs()
    err_console.print(_auth_status_line())

    # A multi-minute silent wait reads as "did this hang?" — the live status
    # line (driven by run_review's on_event callback, one update per tool
    # call / agent dispatch / text chunk) is the difference between that and
    # visible, ongoing progress, the same idea as Claude Code's own spinner.
    with err_console.status("[dim]starting review…[/dim]", spinner="dots") as status:
        def on_event(text: str) -> None:
            status.update(f"[dim]{text}[/dim]")

        result = anyio.run(run_review, None, on_event)

    if not result.report:
        err_console.print("[red]No report produced.[/red]")
        return 1

    out = REPORTS_DIR / f"{date.today().isoformat()}.md"
    footer = (
        f"\n\n---\n*Generated {date.today().isoformat()} · run `{result.run_id}` · "
        f"{result.turns} turns · {len(result.tool_calls)} tool calls · "
        f"{result.duration_s:.0f}s"
        + (f" · ${result.cost_usd:.4f}" if result.cost_usd else "")
        + "*\n"
    )
    out.write_text(result.report + footer, encoding="utf-8")

    err_console.print(f"\n[green]✓[/green] {out}")
    err_console.print(
        f"  [dim]run {result.run_id} · {result.turns} turns · "
        f"{len(result.tool_calls)} tool calls · {result.duration_s:.0f}s"
        + (f" · ${result.cost_usd:.4f}" if result.cost_usd else "") + "[/dim]"
    )

    console.print()
    _render_recommendations(recommendations_for_run(result.run_id))

    if args.show:
        console.print()
        console.print(result.report)
    return 0


def cmd_welcome(args) -> int:
    """No subcommand given — what someone who downloaded the standalone
    executable and double-clicked it actually experiences, as opposed to
    someone who already knows to type `factfolio status`. Runs first-time
    setup if needed, shows an instant status snapshot if there's already a
    portfolio to show one for, and always prints the numbered next step —
    plain terminal output, identical on every platform, never a GUI. Since a
    double-clicked console window on Windows closes itself the instant the
    process exits, this also prints a command menu and waits for a keypress
    afterward rather than vanishing before anyone can read it.
    """
    from mybroker.config import HOLDINGS_EQUITY, HOLDINGS_INBOX_DIR, POLICY_FILE

    print(f"{BOLD}FactFolio{RESET}\n", flush=True)

    first_run = not POLICY_FILE.exists()
    cmd_init(args)  # idempotent — safe whether this is a first run or not

    holdings_ready = HOLDINGS_EQUITY.exists() or any(HOLDINGS_INBOX_DIR.glob("*"))
    if holdings_ready and not first_run:
        print()
        cmd_status(args)

    print(f"\n{BOLD}Other things you can run:{RESET}")
    print(f"  factfolio status      {DIM}instant snapshot, no LLM{RESET}")
    print(f"  factfolio report      {DIM}full multi-agent review{RESET}")
    print(f"  factfolio chat        {DIM}terminal Q&A{RESET}")
    print(f"  factfolio validate    {DIM}resolve tickers — do this before report/chat{RESET}")
    print(f"  factfolio mcp         {DIM}run as an MCP server for other tools{RESET}")
    print(f"  factfolio --help      {DIM}everything{RESET}")

    # Only pause for a frozen build in an actual interactive console — never
    # when piped/scripted (would hang forever waiting for input that never
    # comes), and pip-installed/uv-run users are already at a shell prompt
    # that won't disappear on them regardless.
    if getattr(sys, "frozen", False) and sys.stdin.isatty():
        input(f"\n{DIM}Press Enter to exit…{RESET}")
    return 0


def cmd_init(_args) -> int:
    """First-run setup: create the runtime dirs and a starter policy file.

    Never overwrites an existing memory/investment_policy.md — safe to
    re-run any time (e.g. after adding a new symbol to tickers.yaml).
    """
    from mybroker.config import (
        HOLDINGS_EQUITY,
        HOLDINGS_INBOX_DIR,
        POLICY_FILE,
        SRC_DIR,
    )

    ensure_dirs()

    if POLICY_FILE.exists():
        print(f"{DIM}✓ {POLICY_FILE} already exists — left untouched.{RESET}")
    else:
        POLICY_FILE.write_text(
            _POLICY_TEMPLATE.replace("__TODAY__", date.today().isoformat()),
            encoding="utf-8",
        )
        print(f"{GREEN}✓{RESET} Wrote a starter {POLICY_FILE}")
        print(f"  {DIM}Edit every number in it before relying on any recommendation.{RESET}")

    print(f"\n{BOLD}Next steps{RESET}")
    steps = []
    if not HOLDINGS_EQUITY.exists() and not any(HOLDINGS_INBOX_DIR.glob("*")):
        steps.append(
            f"Add your holdings: export from your broker and place it at "
            f"{HOLDINGS_EQUITY}, or drop any csv/xls/xlsx/pdf/txt export into "
            f"{HOLDINGS_INBOX_DIR}/."
        )
    steps.append(
        f"Add every symbol you hold to {SRC_DIR / 'data' / 'tickers.yaml'} "
        f"(see that file's own header for the format)."
    )
    steps.append("Run `factfolio validate` to resolve every ticker.")
    steps.append("Run `factfolio status` for an instant, LLM-free snapshot.")
    for i, step in enumerate(steps, 1):
        print(f"  {i}. {step}")
    return 0


def cmd_validate(_args) -> int:
    """Re-resolve tickers. The gate that must pass before any agent run."""
    from mybroker.tickers_validate import main as validate_main

    return validate_main()


def cmd_mcp(_args) -> int:
    """Run as a standalone MCP server (stdio) for external clients — VS
    Code's Claude extension, Claude Desktop, or any other MCP-aware tool or
    agent. Point a client at `factfolio mcp`; nothing to configure, no port
    to pick. See mcp_server.py for the exposed tools."""
    from mybroker.mcp_server import run as run_mcp_server

    return run_mcp_server()


def cmd_estimate_dates(_args) -> int:
    """Tentative purchase-date estimation from price history + avg_cost.

    Deterministic, no LLM — one price-history fetch per equity position, then
    portfolio.purchase_estimator's tightest-tolerance-first, most-recent-
    match-first search. Writes memory/estimated_purchase_dates.{json,md}.
    compute_tax_impact reads the json back as a fallback when a sale doesn't
    supply an explicit purchase_date.
    """
    from mybroker.data.yfinance_provider import YFinanceProvider
    from mybroker.portfolio.purchase_estimator import estimate_purchase_date, save_estimates

    portfolio = load_portfolio()
    provider = YFinanceProvider()

    print(f"{DIM}Estimating purchase dates for {len(portfolio.equity)} positions "
          f"(fetching price history)…{RESET}", file=sys.stderr)

    estimates = []
    for pos in portfolio.equity:
        try:
            result = provider.get_history(pos.symbol, days=1100)
        except KeyError as exc:
            print(f"  {YELLOW}{pos.symbol}: skipped — {exc}{RESET}", file=sys.stderr)
            continue

        if not result.data:
            print(f"  {YELLOW}{pos.symbol}: skipped — "
                  f"{'; '.join(result.warnings) or 'no price history'}{RESET}", file=sys.stderr)
            continue

        est = estimate_purchase_date(pos.symbol, pos.avg_cost, result.data)
        estimates.append(est)

        if est.confident:
            print(f"  {GREEN}{pos.symbol:<12}{RESET} → {est.estimated_date}  "
                  f"({est.holding_days_from_today}d ago, ±{est.tolerance_pct:.1f}%)",
                  file=sys.stderr)
        else:
            print(f"  {DIM}{pos.symbol:<12} → no confident match{RESET}", file=sys.stderr)

    save_estimates(estimates)
    n_confident = sum(1 for e in estimates if e.confident)
    print(f"\n{BOLD}{n_confident}/{len(estimates)} estimated{RESET} "
          f"{DIM}→ memory/estimated_purchase_dates.{{json,md}}. "
          f"TENTATIVE — verify against contract notes before filing taxes.{RESET}",
          file=sys.stderr)
    return 0


def cmd_chat(_args) -> int:
    """Interactive REPL. Lighter than `report` — one agent, direct tool
    access, no subagent roster or adversarial review. Q&A, not a new
    recommendation path."""
    from mybroker.agents.chat import run_chat_repl

    return anyio.run(run_chat_repl)


def cmd_cron(args) -> int:
    """M5 unattended job: grade due recommendations against real outcomes.

    Pure Python + one price fetch per due recommendation — no LLM, no agent
    session, safe on a schedule (see docs/MILESTONES.md for a crontab/launchd
    example). Idempotent: re-running finds nothing new to grade. Exit code
    reflects whether the run itself errored, not whether anything was due.
    """
    import json
    from datetime import UTC, datetime

    from mybroker.config import CRON_LOG, ensure_dirs
    from mybroker.scoring import grade_due_recommendations

    ensure_dirs()
    started = datetime.now(UTC)

    try:
        results = grade_due_recommendations()
    except Exception as exc:
        print(f"{RED}✗ cron run failed: {exc}{RESET}", file=sys.stderr)
        with CRON_LOG.open("a", encoding="utf-8") as fh:
            fh.write(json.dumps({"ts": started.isoformat(), "ok": False, "error": str(exc)}) + "\n")
        return 1

    graded = [r for r in results if r.graded]
    ungradeable = [r for r in results if not r.graded]

    with CRON_LOG.open("a", encoding="utf-8") as fh:
        fh.write(json.dumps({
            "ts": started.isoformat(),
            "ok": True,
            "due": len(results),
            "graded": len(graded),
            "ungradeable": len(ungradeable),
            "results": [
                {"rec_id": r.rec_id, "symbol": r.symbol, "action": r.action,
                 "graded": r.graded,
                 **({"verdict": r.outcome.get("verdict"),
                     "return_pct": r.outcome.get("return_pct")} if r.outcome else {}),
                 **({"reason": r.reason} if r.reason else {})}
                for r in results
            ],
        }, default=str) + "\n")

    prefix = f"[{started.strftime('%Y-%m-%d %H:%M')}]"
    if not results:
        print(f"{DIM}{prefix} nothing due for review.{RESET}", file=sys.stderr)
        return 0

    print(f"{BOLD}{prefix} due_for_review: {len(results)}{RESET}", file=sys.stderr)
    for r in graded:
        o = r.outcome or {}
        col = GREEN if (o.get("return_pct") or 0) >= 0 else RED
        verdict = f" — {o.get('verdict')}" if o.get("verdict") else ""
        print(f"  {r.symbol:<12} {r.action:<6} {col}{o.get('return_pct'):+.2f}%{RESET}"
              f"{verdict}  `{r.rec_id}`", file=sys.stderr)
    for r in ungradeable:
        print(f"  {YELLOW}{r.symbol:<12} {r.action:<6} ungradeable — {r.reason}{RESET}",
              file=sys.stderr)
    print(f"{DIM}{len(graded)} graded, {len(ungradeable)} ungradeable "
          f"→ memory/ledger.jsonl updated{RESET}", file=sys.stderr)
    return 0


def main(argv: list[str] | None = None) -> int:
    # Windows only gives stdout/stderr a UTF-8 codepage for an *interactive*
    # console — the moment either is redirected/piped/captured (a CI step,
    # `factfolio status > out.txt`, anything), Python falls back to the
    # legacy codepage (cp1252), which can't encode the ✓/✗/₹ this CLI prints
    # everywhere, and crashes with UnicodeEncodeError before printing
    # anything useful. reconfigure() (Python 3.7+) forces UTF-8 with a safe
    # fallback instead of a crash; harmless no-op on platforms already UTF-8.
    for _stream in (sys.stdout, sys.stderr):
        if hasattr(_stream, "reconfigure"):
            _stream.reconfigure(encoding="utf-8", errors="replace")

    from mybroker import __version__

    parser = argparse.ArgumentParser(
        prog="mybroker",
        description="Indian equity & mutual fund portfolio advisory agent.",
    )
    parser.add_argument("--version", action="version", version=f"factfolio {__version__}")
    # Not required: someone who downloaded the standalone executable and
    # double-clicked it (no terminal, no arguments) should land on
    # cmd_welcome below, not a bare "command required" usage error in a
    # console window that closes itself the instant the process exits.
    parser.set_defaults(func=cmd_welcome)
    sub = parser.add_subparsers(dest="command", required=False)

    sub.add_parser("init", help="first-run setup: dirs + a starter investment_policy.md"
                   ).set_defaults(func=cmd_init)

    sub.add_parser("status", help="deterministic snapshot (no LLM, instant)"
                   ).set_defaults(func=cmd_status)

    p_report = sub.add_parser("report", help="full agent review → reports/")
    p_report.add_argument("--show", action="store_true", help="also print to stdout")
    p_report.set_defaults(func=cmd_report)

    sub.add_parser("validate", help="re-resolve tickers (gate)"
                   ).set_defaults(func=cmd_validate)

    sub.add_parser("mcp", help="run as an MCP server (stdio) for other tools/agents"
                   ).set_defaults(func=cmd_mcp)

    sub.add_parser("estimate-dates",
                    help="tentative purchase-date estimation from price history (no LLM)"
                    ).set_defaults(func=cmd_estimate_dates)

    sub.add_parser("chat", help="interactive Q&A REPL, one agent, no report gate"
                   ).set_defaults(func=cmd_chat)

    sub.add_parser("cron", help="M5: grade due recommendations (no LLM, unattended-safe)"
                   ).set_defaults(func=cmd_cron)

    args = parser.parse_args(argv)
    try:
        return args.func(args)
    except FileNotFoundError as exc:
        print(f"{RED}✗{RESET} {exc}", file=sys.stderr)
        return 1
    except KeyboardInterrupt:
        print("\ninterrupted", file=sys.stderr)
        return 130
    except Exception as exc:
        # Backstop for everything a subcommand didn't handle itself — without
        # this, any uncaught exception (an SDK/network hiccup, a bad broker
        # export, anything) dumps a raw traceback and exits with no hint of
        # what to do next. Show a short, actionable message; keep the full
        # traceback on disk instead of scrolling off the terminal.
        from mybroker.errors import friendly_message, log_error

        log_file = log_error(f"factfolio {args.command}", exc)
        print(f"\n{RED}✗{RESET} `factfolio {args.command}` failed: "
              f"{friendly_message(exc)}", file=sys.stderr)
        if log_file:
            print(f"  {DIM}Full traceback: {log_file}{RESET}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
