"""Command-line interface.

Every interface (CLI, dashboard, chat, cron) calls the same engine, so there is
one implementation of the analysis and four ways to look at it.
"""

from __future__ import annotations

import argparse
import sys
from datetime import date
from pathlib import Path

import anyio

from mybroker.config import REPORTS_DIR, ensure_dirs
from mybroker.portfolio.loader import load_portfolio
from mybroker.portfolio.metrics import snapshot
from mybroker.portfolio.policy import Policy

_POLICY_TEMPLATE = """\
# Investment Policy

**Status:** DRAFT — edit every number below before relying on this.

This is the standard every recommendation is measured against. The agent
does not decide whether a position is too large; this file decides, and
the agent reasons about what to do next. Change the numbers here and the
agent's behaviour changes with them.

The fenced `yaml` block is parsed by the code. The prose around it should
explain *why* each number is what it is, so the two never drift apart —
edit both together.

## Objective

State your target CAGR and horizon here, and why: e.g. "13% CAGR over 10
years — roughly the Nifty's long-run average, prioritising low drawdown
over outperformance."

## Structure: core–satellite

Describe what belongs in each bucket for you (index funds/large-caps vs.
midcap/smallcap/thematic bets), and your current split.

## Position limits

Describe your position/sector/speculative caps and why — the numbers below
are generic starting points, not a recommendation.

## Rebalancing approach

New capital first, or trim-to-cap, or something else — and your rule for
when a sale is actually justified given its tax cost.

---

```yaml
# ── Machine-enforceable limits. Parsed by portfolio/policy.py ──
# Generic starting values — replace every one of these with your own.
target_cagr_pct: 12.0

core_min_pct: 60.0
core_max_pct: 70.0

# Optional dated glidepath — delete this block entirely to use core_min_pct
# as a flat target from day one instead of a phased-in one.
# glidepath_start: YYYY-MM-DD
# glidepath:
#   - {months: 6,  core_pct: 30.0}
#   - {months: 12, core_pct: 45.0}

max_position_pct: 8.0                 # any single core holding
max_satellite_position_pct: 5.0       # any single satellite holding
max_sector_pct: 25.0                  # any one sector

speculative_cap_pct: 10.0
speculative_symbols: []               # e.g. [IDEA, YESBANK] — binary-outcome names

min_positions: 8
max_positions: 25

monthly_capital: 0                    # new capital available per month, in ₹
max_annual_turnover_pct: 25.0
```

---

## Change log

| Date | Change |
|---|---|
| __TODAY__ | Generated by `factfolio init`. Not yet customised or approved. |
"""

DIM, BOLD, RESET = "\033[2m", "\033[1m", "\033[0m"
RED, YELLOW, GREEN = "\033[31m", "\033[33m", "\033[32m"

SEVERITY_COLOR = {"critical": RED, "high": RED, "medium": YELLOW, "low": DIM}


def _auth_status_line() -> str:
    """Which credential the Claude Agent SDK will actually use.

    Neither `agents/orchestrator.py` nor `agents/chat.py` sets an API key —
    the subprocess just inherits this process's environment, so the
    resolution is entirely the `claude` CLI's own: ANTHROPIC_API_KEY, if
    set, wins; otherwise it falls back to a local `claude login` session.
    Local login is therefore the default with zero configuration, and
    exporting the env var is the override — never the other way around.
    """
    import os

    if os.environ.get("ANTHROPIC_API_KEY"):
        return f"{DIM}auth: ANTHROPIC_API_KEY (env var override){RESET}"
    return f"{DIM}auth: local `claude login` session (no ANTHROPIC_API_KEY set){RESET}"


def cmd_status(_args) -> int:
    """Deterministic portfolio status. No LLM, no network, instant."""
    snap = snapshot(load_portfolio())
    pol = Policy.load()
    target, step = pol.current_core_target()

    print(f"\n{BOLD}Portfolio{RESET}  {DIM}(from holdings.csv){RESET}")
    print(f"  Invested       ₹{snap.total_invested:>14,.2f}")
    print(f"  Current        ₹{snap.total_value:>14,.2f}")
    pnl_col = GREEN if snap.total_pnl >= 0 else RED
    print(f"  P&L            {pnl_col}₹{snap.total_pnl:>14,.2f}  "
          f"({snap.total_pnl_pct:+.2f}%){RESET}")

    print(f"\n{BOLD}Allocation{RESET}")
    print(f"  Core           {snap.core_pct:>6.1f}%   "
          f"{DIM}target now {target:.0f}% ({step}); final {pol.core_min_pct:.0f}%{RESET}")
    print(f"  Satellite      {snap.satellite_pct:>6.1f}%")

    print(f"\n{BOLD}Top positions{RESET}")
    for w in snap.positions[:8]:
        col = GREEN if w.pnl >= 0 else RED
        print(f"  {w.key:<11} {w.weight_pct:>5.1f}%  ₹{w.value:>11,.0f}  "
              f"{col}{w.pnl_pct:>+7.1f}%{RESET}  {DIM}{w.sector}{RESET}")

    print(f"\n{BOLD}Sectors{RESET}")
    for w in snap.sectors[:6]:
        flag = f" {RED}← over {pol.max_sector_pct:.0f}% cap{RESET}" if (
            w.weight_pct > pol.max_sector_pct) else ""
        print(f"  {w.key:<22} {w.weight_pct:>5.1f}%{flag}")

    breaches = pol.check(snap)
    print(f"\n{BOLD}Policy{RESET}  {DIM}({len(breaches)} breaches){RESET}")
    for b in breaches[:10]:
        c = SEVERITY_COLOR.get(b.severity, "")
        print(f"  {c}[{b.severity:<8}]{RESET} {b.subject:<22} "
              f"{b.actual:>6.1f}% vs {b.limit:.0f}%")
    if len(breaches) > 10:
        print(f"  {DIM}… and {len(breaches) - 10} more{RESET}")

    pc, sc = snap.position_concentration, snap.sector_concentration
    print(f"\n{BOLD}Concentration{RESET}")
    print(f"  Position HHI   {pc.hhi:>6.0f}  ({pc.verdict})")
    print(f"  Sector HHI     {sc.hhi:>6.0f}  ({sc.verdict})")
    if sc.hhi > pc.hhi:
        print(f"  {DIM}Sector HHI exceeds position HHI — position-level HHI is{RESET}")
        print(f"  {DIM}correlation-blind, so the sector reading is the honest one.{RESET}")

    for w in snap.warnings:
        print(f"\n  {YELLOW}!{RESET} {w}")
    print()
    return 0


def cmd_report(args) -> int:
    """Full agent-generated review, written to reports/YYYY-MM-DD.md."""
    from mybroker.agents.orchestrator import run_review

    ensure_dirs()
    print(_auth_status_line(), file=sys.stderr)
    print(f"{DIM}Running review… this takes a few minutes.{RESET}", file=sys.stderr)

    result = anyio.run(run_review)

    if not result.report:
        print(f"{RED}No report produced.{RESET}", file=sys.stderr)
        return 1

    out = REPORTS_DIR / f"{date.today().isoformat()}.md"
    footer = (
        f"\n\n---\n*Generated {date.today().isoformat()} · run `{result.run_id}` · "
        f"{result.turns} turns · {len(result.tool_calls)} tool calls · "
        f"{result.duration_s:.0f}s"
        + (f" · ${result.cost_usd:.4f}" if result.cost_usd else "")
        + "*\n"
    )
    out.write_text(result.report + footer, encoding="utf-8")

    print(f"\n{GREEN}✓{RESET} {out}", file=sys.stderr)
    print(f"  {DIM}run {result.run_id} · {result.turns} turns · "
          f"{len(result.tool_calls)} tool calls · {result.duration_s:.0f}s"
          + (f" · ${result.cost_usd:.4f}" if result.cost_usd else "") + f"{RESET}",
          file=sys.stderr)

    if args.show:
        print(result.report)
    return 0


def cmd_init(_args) -> int:
    """First-run setup: create the runtime dirs and a starter policy file.

    Never overwrites an existing memory/investment_policy.md — safe to
    re-run any time (e.g. after adding a new symbol to tickers.yaml).
    """
    from mybroker.config import (
        HOLDINGS_EQUITY,
        HOLDINGS_INBOX_DIR,
        POLICY_FILE,
        SRC_DIR,
    )

    ensure_dirs()

    if POLICY_FILE.exists():
        print(f"{DIM}✓ {POLICY_FILE} already exists — left untouched.{RESET}")
    else:
        POLICY_FILE.write_text(
            _POLICY_TEMPLATE.replace("__TODAY__", date.today().isoformat()),
            encoding="utf-8",
        )
        print(f"{GREEN}✓{RESET} Wrote a starter {POLICY_FILE}")
        print(f"  {DIM}Edit every number in it before relying on any recommendation.{RESET}")

    print(f"\n{BOLD}Next steps{RESET}")
    steps = []
    if not HOLDINGS_EQUITY.exists() and not any(HOLDINGS_INBOX_DIR.glob("*")):
        steps.append(
            f"Add your holdings: export from your broker and place it at "
            f"{HOLDINGS_EQUITY}, or drop any csv/xls/xlsx/pdf export into "
            f"{HOLDINGS_INBOX_DIR}/."
        )
    steps.append(
        f"Add every symbol you hold to {SRC_DIR / 'data' / 'tickers.yaml'} "
        f"(see that file's own header for the format)."
    )
    steps.append("Run `factfolio validate` to resolve every ticker.")
    steps.append("Run `factfolio status` for an instant, LLM-free snapshot.")
    for i, step in enumerate(steps, 1):
        print(f"  {i}. {step}")
    return 0


def cmd_validate(_args) -> int:
    """Re-resolve tickers. The gate that must pass before any agent run."""
    from mybroker.tickers_validate import main as validate_main

    return validate_main()


def cmd_dashboard(_args) -> int:
    """Launch the Streamlit dashboard. Same engine as `status`, visual."""
    dashboard_path = Path(__file__).with_name("dashboard.py")
    print(f"{DIM}Launching dashboard… (Ctrl+C to stop){RESET}", file=sys.stderr)

    if getattr(sys, "frozen", False):
        # A PyInstaller build: sys.executable IS this frozen binary, not a
        # real Python interpreter, so `sys.executable -m streamlit run ...`
        # below can't work (it would just re-invoke this same CLI). Streamlit
        # has no PyInstaller hook of its own, so the build (see
        # packaging/factfolio.spec) bundles dashboard.py as a literal data
        # file and streamlit's own static assets via collect_all("streamlit")
        # — bootstrap.run() is what `streamlit run` itself calls, in-process.
        from streamlit.web import bootstrap

        bootstrap.run(str(dashboard_path), False, [], {})
        return 0

    import subprocess

    return subprocess.call(
        [sys.executable, "-m", "streamlit", "run", str(dashboard_path)]
    )


def cmd_estimate_dates(_args) -> int:
    """Tentative purchase-date estimation from price history + avg_cost.

    Deterministic, no LLM — one price-history fetch per equity position, then
    portfolio.purchase_estimator's tightest-tolerance-first, most-recent-
    match-first search. Writes memory/estimated_purchase_dates.{json,md}.
    compute_tax_impact reads the json back as a fallback when a sale doesn't
    supply an explicit purchase_date.
    """
    from mybroker.data.yfinance_provider import YFinanceProvider
    from mybroker.portfolio.purchase_estimator import estimate_purchase_date, save_estimates

    portfolio = load_portfolio()
    provider = YFinanceProvider()

    print(f"{DIM}Estimating purchase dates for {len(portfolio.equity)} positions "
          f"(fetching price history)…{RESET}", file=sys.stderr)

    estimates = []
    for pos in portfolio.equity:
        try:
            result = provider.get_history(pos.symbol, days=1100)
        except KeyError as exc:
            print(f"  {YELLOW}{pos.symbol}: skipped — {exc}{RESET}", file=sys.stderr)
            continue

        if not result.data:
            print(f"  {YELLOW}{pos.symbol}: skipped — "
                  f"{'; '.join(result.warnings) or 'no price history'}{RESET}", file=sys.stderr)
            continue

        est = estimate_purchase_date(pos.symbol, pos.avg_cost, result.data)
        estimates.append(est)

        if est.confident:
            print(f"  {GREEN}{pos.symbol:<12}{RESET} → {est.estimated_date}  "
                  f"({est.holding_days_from_today}d ago, ±{est.tolerance_pct:.1f}%)",
                  file=sys.stderr)
        else:
            print(f"  {DIM}{pos.symbol:<12} → no confident match{RESET}", file=sys.stderr)

    save_estimates(estimates)
    n_confident = sum(1 for e in estimates if e.confident)
    print(f"\n{BOLD}{n_confident}/{len(estimates)} estimated{RESET} "
          f"{DIM}→ memory/estimated_purchase_dates.{{json,md}}. "
          f"TENTATIVE — verify against contract notes before filing taxes.{RESET}",
          file=sys.stderr)
    return 0


def cmd_chat(_args) -> int:
    """Interactive REPL. Lighter than `report` — one agent, direct tool
    access, no subagent roster or adversarial review. Q&A, not a new
    recommendation path."""
    from mybroker.agents.chat import run_chat_repl

    return anyio.run(run_chat_repl)


def cmd_cron(args) -> int:
    """M5 unattended job: grade due recommendations against real outcomes.

    Pure Python + one price fetch per due recommendation — no LLM, no agent
    session, safe on a schedule (see docs/MILESTONES.md for a crontab/launchd
    example). Idempotent: re-running finds nothing new to grade. Exit code
    reflects whether the run itself errored, not whether anything was due.
    """
    import json
    from datetime import UTC, datetime

    from mybroker.config import CRON_LOG, ensure_dirs
    from mybroker.scoring import grade_due_recommendations

    ensure_dirs()
    started = datetime.now(UTC)

    try:
        results = grade_due_recommendations()
    except Exception as exc:
        print(f"{RED}✗ cron run failed: {exc}{RESET}", file=sys.stderr)
        with CRON_LOG.open("a", encoding="utf-8") as fh:
            fh.write(json.dumps({"ts": started.isoformat(), "ok": False, "error": str(exc)}) + "\n")
        return 1

    graded = [r for r in results if r.graded]
    ungradeable = [r for r in results if not r.graded]

    with CRON_LOG.open("a", encoding="utf-8") as fh:
        fh.write(json.dumps({
            "ts": started.isoformat(),
            "ok": True,
            "due": len(results),
            "graded": len(graded),
            "ungradeable": len(ungradeable),
            "results": [
                {"rec_id": r.rec_id, "symbol": r.symbol, "action": r.action,
                 "graded": r.graded,
                 **({"verdict": r.outcome.get("verdict"),
                     "return_pct": r.outcome.get("return_pct")} if r.outcome else {}),
                 **({"reason": r.reason} if r.reason else {})}
                for r in results
            ],
        }, default=str) + "\n")

    prefix = f"[{started.strftime('%Y-%m-%d %H:%M')}]"
    if not results:
        print(f"{DIM}{prefix} nothing due for review.{RESET}", file=sys.stderr)
        return 0

    print(f"{BOLD}{prefix} due_for_review: {len(results)}{RESET}", file=sys.stderr)
    for r in graded:
        o = r.outcome or {}
        col = GREEN if (o.get("return_pct") or 0) >= 0 else RED
        verdict = f" — {o.get('verdict')}" if o.get("verdict") else ""
        print(f"  {r.symbol:<12} {r.action:<6} {col}{o.get('return_pct'):+.2f}%{RESET}"
              f"{verdict}  `{r.rec_id}`", file=sys.stderr)
    for r in ungradeable:
        print(f"  {YELLOW}{r.symbol:<12} {r.action:<6} ungradeable — {r.reason}{RESET}",
              file=sys.stderr)
    print(f"{DIM}{len(graded)} graded, {len(ungradeable)} ungradeable "
          f"→ memory/ledger.jsonl updated{RESET}", file=sys.stderr)
    return 0


def main(argv: list[str] | None = None) -> int:
    from mybroker import __version__

    parser = argparse.ArgumentParser(
        prog="mybroker",
        description="Indian equity & mutual fund portfolio advisory agent.",
    )
    parser.add_argument("--version", action="version", version=f"factfolio {__version__}")
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("init", help="first-run setup: dirs + a starter investment_policy.md"
                   ).set_defaults(func=cmd_init)

    sub.add_parser("status", help="deterministic snapshot (no LLM, instant)"
                   ).set_defaults(func=cmd_status)

    p_report = sub.add_parser("report", help="full agent review → reports/")
    p_report.add_argument("--show", action="store_true", help="also print to stdout")
    p_report.set_defaults(func=cmd_report)

    sub.add_parser("validate", help="re-resolve tickers (gate)"
                   ).set_defaults(func=cmd_validate)

    sub.add_parser("dashboard", help="launch the Streamlit dashboard (no LLM)"
                   ).set_defaults(func=cmd_dashboard)

    sub.add_parser("estimate-dates",
                    help="tentative purchase-date estimation from price history (no LLM)"
                    ).set_defaults(func=cmd_estimate_dates)

    sub.add_parser("chat", help="interactive Q&A REPL, one agent, no report gate"
                   ).set_defaults(func=cmd_chat)

    sub.add_parser("cron", help="M5: grade due recommendations (no LLM, unattended-safe)"
                   ).set_defaults(func=cmd_cron)

    args = parser.parse_args(argv)
    try:
        return args.func(args)
    except FileNotFoundError as exc:
        print(f"{RED}✗{RESET} {exc}", file=sys.stderr)
        return 1
    except KeyboardInterrupt:
        print("\ninterrupted", file=sys.stderr)
        return 130
    except Exception as exc:
        # Backstop for everything a subcommand didn't handle itself — without
        # this, any uncaught exception (an SDK/network hiccup, a bad broker
        # export, anything) dumps a raw traceback and exits with no hint of
        # what to do next. Show a short, actionable message; keep the full
        # traceback on disk instead of scrolling off the terminal.
        from mybroker.errors import friendly_message, log_error

        log_file = log_error(f"factfolio {args.command}", exc)
        print(f"\n{RED}✗{RESET} `factfolio {args.command}` failed: "
              f"{friendly_message(exc)}", file=sys.stderr)
        if log_file:
            print(f"  {DIM}Full traceback: {log_file}{RESET}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
